apps/cms/views.py
from flask import Blueprint, views, render_template, request, session,\
    redirect, url_for, g, jsonify
from .forms import LoginForm, ResetpwdForm, ResetemailForm, AddBannerForm, \
    UpdateBannerForm, AddBoardForm, UpdateBoardForm
from .models import CmsUser, CmsPermission
import config
from .decorators import Login_required, Permission_required
from exts import db, mail
from utils import restful, cache
from flask_mail import Message
import string
import random
from ..models import BannerModel, BoardModel, PostModel, HighlightPostModel





bp = Blueprint('cms', __name__, url_prefix="/cms")


@bp.route('/')
@Login_required
def index():
    return render_template('cms/cms_index.html')


@bp.route('/logout')
@Login_required
def logout():
    del session[config.cms_user_id]
    return redirect(url_for('cms.login'))


@bp.route('/profile')
@Login_required
def profile():
    return render_template('cms/cms_profile.html')


# test email 1
@bp.route('/email/')
def sent_email():
    message = Message('邮件发送', recipients=['250972096@qq.com'], body='测试')
    mail.send(message)
    print('success')
    return 'success'


# test email 2
@bp.route('/email_captcha/')
@Login_required
def email_captcha():
    #     /email_captcha/?email=xxx@qq.com
    email = request.args.get('email')
    if not email:
        return restful.params_error("请传入邮箱参数")
    source = list(string.ascii_letters)
    source.extend(map(lambda x: str(x), range(0, 10)))
    captcha = "".join(random.sample(source, 6))

    message = Message('验证码', recipients=[email], body='您的论坛验证码是：%s' % captcha)
    try:
        mail.send(message)
    except:
        return restful.server_error()
    cache.set(email, captcha)
    return restful.success()


@bp.route('/posts/')
@Login_required
@Permission_required(CmsPermission.POSTER)
def posts():
    post_list = PostModel.query.all()
    return render_template('cms/cms_posts.html', posts=post_list)


@bp.route('/hpost/', methods=["POST"])
@Login_required
@Permission_required(CmsPermission.POSTER)
def hpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error('请传入帖子id！')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这个帖子！')
    highlight = HighlightPostModel()
    highlight.post = post
    db.session.add(highlight)
    db.session.commit()
    return restful.success()


@bp.route('/dhpost/', methods=['POST'])
@Login_required
@Permission_required(CmsPermission.POSTER)
def dhpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error('请传入帖子id！')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')

    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()


@bp.route('/comments/')
@Login_required
@Permission_required(CmsPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


@bp.route('/boards/')
@Login_required
@Permission_required(CmsPermission.BOARDER)
def boards():
    board_model = BoardModel.query.all()
    context = {
        'boards': board_model
    }
    return render_template('cms/cms_boards.html', **context)


@bp.route('/aboard/', methods=["POST"])
@Login_required
@Permission_required(CmsPermission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(form.get_error())


@bp.route('/uboard/', methods=["POST"])
@Login_required
@Permission_required(CmsPermission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个板块')
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dboard/', methods=['POST'])
@Login_required
@Permission_required(CmsPermission.BOARDER)
def dboard():
    board_id = request.form.get("board_id")
    print(board_id)
    if not board_id:
        return '请传入需要删除板块的id'
    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message='没有这个板块！')

    db.session.delete(board)
    db.session.commit()
    return restful.success()



@bp.route('/fusers/')
@Login_required
@Permission_required(CmsPermission.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')


@bp.route('/cusers/')
@Login_required
@Permission_required(CmsPermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


@bp.route('/croles/')
@Login_required
@Permission_required(CmsPermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')


@bp.route('/banners/')
@Login_required
@Permission_required(CmsPermission.BANNER)
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html', banners=banners)


@bp.route('/addbanner/', methods=['POST'])
@Login_required
@Permission_required(CmsPermission.BANNER)
def addbanner():
    form = AddBannerForm(request.form)
    if form.validate():
        print('banner')
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/ubanner/', methods=['POST'])
@Login_required
@Permission_required(CmsPermission.BANNER)
def ubanner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个轮播图！')
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dbanner/', methods=['POST'])
@Login_required
@Permission_required(CmsPermission.BANNER)
def dbanner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_error(message='请传入轮播图id！')
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.params_error(message='没有这个轮播图')
    db.session.delete(banner)
    db.session.commit()
    return restful.success()


class LoginView(views.MethodView):

    def get(self, message=None):
        return render_template('cms/cms_login.html', message=message)

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            # 数据库查询时，是查询模型对象，也可以针对模型
            # 过滤有两种方法：filter，filter_by,后者的功能比较强大
            user = CmsUser.query.filter(CmsUser.email == email).first()
            if user and user.check_password(password):
                session[config.cms_user_id] = user.id
                if remember:
                    # 如果设置session.permanent = True,那么过期时间是31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或密码错误')
        else:
            message = form.get_error()
            return self.get(message=message)


class ResetPwdView(views.MethodView):
    decorators = [Login_required]

    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        # print('hello')
        form = ResetpwdForm(request.form)
        if form.validate():
            oldpassword = form.oldpwd.data
            newpassword = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpassword):
                user.password = newpassword
                db.session.commit()
                return restful.success()
            else:
                return restful.params_error('旧密码错误')
        else:
            message = form.get_error()
            print('表单错误')
            return restful.params_error(message)


# 以下为zlbbs3代码
class ResetEmailView(views.MethodView):
    decorators = [Login_required]
    def get(self):
        return render_template('cms/cms_resetemail.html')
    def post(self):
        form = ResetemailForm(request.form)
        if form.validate():
            user = CmsUser.query.filter(CmsUser.email == form.email.data).first()
            if not user:
                email = form.email.data
                g.cms_user.email = email
                db.session.commit()
                return restful.success()
            else:
                return restful.params_error('错误，您输入的邮箱已存在！')
        else:
            return restful.params_error(form.get_error())

bp.add_url_rule('/login/',view_func=LoginView.as_view('login'))
bp.add_url_rule('/resetpwd/',view_func=ResetPwdView.as_view('resetpwd'))
bp.add_url_rule('/resetemail/',view_func=ResetEmailView.as_view('resetemail'))

apps/front/views.py
from flask import Blueprint, render_template, views, make_response, request, \
    url_for, session, redirect, g, abort
from utils.captcha import Captcha
from io import BytesIO
from utils.alidayu import sms
from .forms import SignupForm, SigninForm, AddPostFrom, AddCommentForm
from .models import FrontUser
from exts import db
from utils import restful, safeutils
import config
from ..models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPostModel
from .decorators import Login_required
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy.sql import func

bp = Blueprint('front', __name__)


@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st', type=int, default=1)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(3)
    boards = BoardModel.query.all()
    start = (page-1)*config.per_page
    end = start + config.per_page
    posts = None
    total = 0

    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).\
            order_by(HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id)\
            .order_by(func.count(CommentModel.id).desc(), PostModel.create_time.desc())
    if board_id:
        posts = query_obj.filter(PostModel.board_id == board_id).slice(start, end)
        total = query_obj.filter(PostModel.board_id == board_id).count()
        # outer_window,inner_window是调整显示页面标志的样式的
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total,
                            outer_window=0, inner_window=2)
    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort
    }
    return render_template('front/front_index.html', **context)


@bp.route('/apost/', methods=['GET', 'POST'])
@Login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostFrom(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


@bp.route('/p/<post_id>')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)


@bp.route('/acomment/', methods=['POST'])
@Login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error("没有这篇帖子！")
    else:
        return restful.params_error(form.get_error())


# @bp.route('/captcha/')
# def graph_captcha():
#     text, image = Captcha.gene_graph_captcha()
#     out = BytesIO()
#     image.save(out, 'png')
#     out.seek(0)
#     resp = make_response(out.read())
#     resp.content_type = 'image/png'
#     return resp
#
#
# @bp.route('/sms-captcha/')
# def sms_captcha():
#     result = sms.send('13060867339', {'code': 'asdf'})
#     if result:
#         return '发送成功'
#     else:
#         return '发送失败'


class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template("front/front_signup.html", return_to=return_to)
        return render_template("front/front_signup.html")



    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.errors)
            return restful.params_error(message=form.get_error())



class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data
            user = FrontUser.query.filter(FrontUser.telephone == telephone).first()
            if user and user.check_password(password):
                session[config.front_user_id] = user.id
                if remember:
                    # 如果设置session.permanent = True
                    # 那么过期时间是31天
                    session.permanent = True
                return restful.success()
            else:

                return restful.params_error(message='手机号或密码错误！')
        else:
            print(form.errors)
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}轮播图管理{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/banners.js') }}"></script>
    <style>
        .top-box button {
            float: right;
        }
    </style>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal"
                data-target="#banner-dialog">添加轮播图
        </button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>名称</th>
            <th>图片链接</th>
            <th>跳转链接</th>
            <th>优先级</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
            {% for banner in banners %}
                <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}" data-id="{{ banner.id }}" >
                    <td>{{ banner.name }}</td>
                    <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                    <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


 <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">轮播图</h4>
      </div>
      <div class="modal-body">
          <form action="" class="form-horizontal">
              <div class="form-group">
                  <label class="col-sm-2 control-label">名称：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                  </div>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">图片：</label>
                  <div class="col-sm-7">
                      <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                  </div>
                  <button class="btn btn-info col-sm-2" id="upload-btn">添加图片</button>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">跳转：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                  </div>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">权重：</label>
                  <div class="col-sm-10">
                      <input type="number" class="form-control" name="priority" placeholder="优先级">
                  </div>
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/cms/cms_base.html
{% from "common/_macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include "common/_heads.html" %}
    <link rel="stylesheet" href={{ static('cms/css/base.css') }}>
    <script src="{{ static('cms/js/base.js') }}"></script>

    {% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">知了课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

     <div class="container-fluid">
         <div class="row">
             <div class="col-sm-3 col-md-2 sidebar">
                 <ul class="nav-sidebar">
                     <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                     <li class="profile-li">
                         <a href="#">个人中心<span></span></a>
                         <ul class="subnav">
                             <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                             <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                             <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                         </ul>
                     </li>
                     {% set cms_user = g.cms_user %}
                     {% if cms_user.has_permission(CmsPermission.BANNER) %}
                         <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                     {% endif %}
                     {% if cms_user.has_permission(CmsPermission.POSTER) %}
                         <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                     {% endif %}
                     {% if cms_user.has_permission(CmsPermission.COMMENTER) %}
                         <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                     {% endif %}
                     {% if cms_user.has_permission(CmsPermission.BOARDER) %}
                          <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                     {% endif %}
                     {% if cms_user.has_permission(CmsPermission.FRONTUSER) %}
                          <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
                     {% endif %}
                     {% if cms_user.has_permission(CmsPermission.CMSUSER) %}
                          <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                     {% endif %}
                     {% if cms_user.is_developer %}
                         <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
                     {% endif %}
                 </ul>
             </div>
             <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                 <h1>{% block page_title %}{% endblock %}</h1>
                 <div class="main_content">
                     {% block main_content %}{% endblock %}
                 </div>
             </div>
         </div>
     </div>
</body>
</html>

templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{% from "common/_macros.html" import static %}

{% block title %}板块管理{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" style="float:right;" id="add-board-btn">添加新板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>板块名称</th>
                <th>帖子数量</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                    <td>{{ board.name }}</td>
                    <td>0</td>
                    <td>{{ board.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block title %}评论管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是评论管理页面
{% endblock %}

templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}

{% block title %}CMS角色管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是CMS角色管理页面
{% endblock %}

templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}CMS用户管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是CMS用户管理页面
{% endblock %}

templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}前台用户管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    我是前台用户管理页面
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到知了课堂CMS管理系统
{% endblock %}

templates/cms/cms_login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">


    <title>cms登录界面</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='cms/css/signin.css') }}" rel="stylesheet">


  </head>

  <body>

    <div class="container">

      <form class="form-signin"method="post">
        <h2 class="form-signin-heading">请登录</h2>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="inputEmail" class="sr-only">邮箱</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="邮箱" name="email" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="1" name="remember"> 记住我
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">立即登录</button>
      </form>

    </div> <!-- /container -->

  {% if message %}
      <p style="text-align: center;" class="text-danger">{{ message }}</p>
  {% endif %}

  </body>
</html>

templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{% from "common/_macros.html" import static %}

{% block title %}帖子管理{% endblock %}

{% block head %}
    <script src="{{ static("cms/js/posts.js") }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table-bordered">
        <thead>
            <tr>
                <th>标题</th>
                <th>发布时间</th>
                <th>板块</th>
                <th>作者</th>
                <th>操作</th>
            </tr>
        </thead>
    <tbody>
        {% for post in posts %}
            <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">
                <td><a target="_blank" href="{{ url_for("front.post_detail", post_id=post.id) }}">{{ post.title }}</a></td>
                <td>{{ post.create_time }}</td>
                <td>{{ post.board.name }}</td>
                <td>{{ post.author.username }}</td>
                <td>
                    {% if post.highlight %}
                        <button class="btn btn-default btn-xs highlight-btn">取消加精</button>
                    {% else %}
                        <button class="btn btn-default btn-xs highlight-btn">加精</button>
                    {% endif %}
                    <button class="btn btn-danger btn-xs">移除</button>
                </td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

templates/cms/cms_profile.html
{% extends 'cms/cms_base.html' %}
{% block title %}
    个人信息
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    {% set user = g.cms_user %}
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>用户名：</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>邮箱：</td>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <td>角色：</td>
            <td>
                {% for role in user.roles %}
                    {{ role.name }}
                    {% if not loop.last %},{% endif %}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>权限：</td>
            <td>
                {% for role in user.roles %}
                    {{ role.desc }}
                    {% if not loop.last %}/{% endif %}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>加入时间：</td>
            <td>{{ user.join_time }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}